"""
airport_lookup.py - Static airport name lookup.

Maps truncated names from old-format invoices and IATA codes to full airport names.
No API calls. Runs instantly. Add entries as new airports appear in invoices.
"""

# ── IATA code -> (Full Airport Name, City) ────────────────────
# Covers major airports Travel Wizards clients would use.
# Add new codes as they appear in invoices.
IATA = {
    # North America - US
    "ANC": ("Ted Stevens Anchorage Intl", "Anchorage"),
    "ATL": ("Hartsfield-Jackson Atlanta Intl", "Atlanta"),
    "AUS": ("Austin-Bergstrom Intl", "Austin"),
    "BNA": ("Nashville Intl", "Nashville"),
    "BOS": ("Logan Intl", "Boston"),
    "BUR": ("Hollywood Burbank", "Burbank"),
    "BWI": ("Baltimore/Washington Intl", "Baltimore"),
    "CLE": ("Cleveland Hopkins Intl", "Cleveland"),
    "CLT": ("Charlotte Douglas Intl", "Charlotte"),
    "DCA": ("Ronald Reagan Washington National", "Washington DC"),
    "DEN": ("Denver Intl", "Denver"),
    "DFW": ("Dallas/Fort Worth Intl", "Dallas"),
    "DTW": ("Detroit Metropolitan Wayne County", "Detroit"),
    "EWR": ("Newark Liberty Intl", "Newark"),
    "FLL": ("Fort Lauderdale-Hollywood Intl", "Fort Lauderdale"),
    "HNL": ("Daniel K. Inouye Intl", "Honolulu"),
    "IAD": ("Washington Dulles Intl", "Washington DC"),
    "IAH": ("George Bush Intercontinental", "Houston"),
    "IND": ("Indianapolis Intl", "Indianapolis"),
    "JFK": ("John F. Kennedy Intl", "New York"),
    "LAS": ("Harry Reid Intl", "Las Vegas"),
    "LAX": ("Los Angeles Intl", "Los Angeles"),
    "LGA": ("LaGuardia", "New York"),
    "MCI": ("Kansas City Intl", "Kansas City"),
    "MCO": ("Orlando Intl", "Orlando"),
    "MDW": ("Chicago Midway Intl", "Chicago"),
    "MIA": ("Miami Intl", "Miami"),
    "MRS": ("Marseille Provence Airport", "Marignane"),
    "MSP": ("Minneapolis-St Paul Intl", "Minneapolis"),
    "MSY": ("Louis Armstrong New Orleans Intl", "New Orleans"),
    "OAK": ("Oakland Intl", "Oakland"),
    "ONT": ("Ontario Intl", "Ontario"),
    "ORD": ("O'Hare Intl", "Chicago"),
    "PBI": ("Palm Beach Intl", "West Palm Beach"),
    "PDX": ("Portland Intl", "Portland"),
    "PHL": ("Philadelphia Intl", "Philadelphia"),
    "PHX": ("Phoenix Sky Harbor Intl", "Phoenix"),
    "PIT": ("Pittsburgh Intl", "Pittsburgh"),
    "RDU": ("Raleigh-Durham Intl", "Raleigh"),
    "RSW": ("Southwest Florida Intl", "Fort Myers"),
    "SAN": ("San Diego Intl", "San Diego"),
    "SAT": ("San Antonio Intl", "San Antonio"),
    "SEA": ("Seattle-Tacoma Intl", "Seattle"),
    "SFO": ("San Francisco Intl", "San Francisco"),
    "SJC": ("San Jose Intl", "San Jose"),
    "SLC": ("Salt Lake City Intl", "Salt Lake City"),
    "SMF": ("Sacramento Intl", "Sacramento"),
    "SNA": ("John Wayne/Orange County", "Santa Ana"),
    "SRQ": ("Sarasota Bradenton Intl", "Sarasota"),
    "STL": ("St. Louis Lambert Intl", "St. Louis"),
    "TPA": ("Tampa Intl", "Tampa"),

    # North America - Canada
    "YEG": ("Edmonton Intl", "Edmonton"),
    "YOW": ("Ottawa Macdonald-Cartier Intl", "Ottawa"),
    "YUL": ("Montreal-Trudeau Intl", "Montreal"),
    "YVR": ("Vancouver Intl", "Vancouver"),
    "YYC": ("Calgary Intl", "Calgary"),
    "YYZ": ("Toronto Pearson Intl", "Toronto"),

    # North America - Mexico / Caribbean
    "CUN": ("Cancun Intl", "Cancun"),
    "GDL": ("Guadalajara Intl", "Guadalajara"),
    "MEX": ("Mexico City Intl", "Mexico City"),
    "MBJ": ("Sangster Intl", "Montego Bay"),
    "NAS": ("Lynden Pindling Intl", "Nassau"),
    "PUJ": ("Punta Cana Intl", "Punta Cana"),
    "PVR": ("Gustavo Diaz Ordaz Intl", "Puerto Vallarta"),
    "SJD": ("Los Cabos Intl", "San Jose del Cabo"),
    "SJU": ("Luis Munoz Marin Intl", "San Juan"),

    # Europe
    "AMS": ("Amsterdam Schiphol", "Amsterdam"),
    "ATH": ("Athens Intl", "Athens"),
    "BCN": ("Barcelona-El Prat", "Barcelona"),
    "BRU": ("Brussels Airport", "Brussels"),
    "CDG": ("Charles de Gaulle", "Paris"),
    "CPH": ("Copenhagen Airport", "Copenhagen"),
    "DUB": ("Dublin Airport", "Dublin"),
    "DUS": ("Dusseldorf Airport", "Dusseldorf"),
    "EDI": ("Edinburgh Airport", "Edinburgh"),
    "FCO": ("Leonardo da Vinci-Fiumicino", "Rome"),
    "FRA": ("Frankfurt Airport", "Frankfurt"),
    "GVA": ("Geneva Airport", "Geneva"),
    "HEL": ("Helsinki-Vantaa", "Helsinki"),
    "IST": ("Istanbul Airport", "Istanbul"),
    "LGW": ("London Gatwick", "London"),
    "LHR": ("London Heathrow", "London"),
    "LIS": ("Humberto Delgado Airport", "Lisbon"),
    "MAD": ("Adolfo Suarez Madrid-Barajas", "Madrid"),
    "MAN": ("Manchester Airport", "Manchester"),
    "MUC": ("Munich Airport", "Munich"),
    "MXP": ("Milan Malpensa", "Milan"),
    "NCE": ("Nice Cote d'Azur", "Nice"),
    "ORY": ("Paris Orly", "Paris"),
    "OSL": ("Oslo Gardermoen", "Oslo"),
    "PRG": ("Vaclav Havel Airport", "Prague"),
    "STN": ("London Stansted", "London"),
    "VCE": ("Venice Marco Polo", "Venice"),
    "VIE": ("Vienna Intl", "Vienna"),
    "ZRH": ("Zurich Airport", "Zurich"),

    # Asia-Pacific
    "BKK": ("Suvarnabhumi Airport", "Bangkok"),
    "DEL": ("Indira Gandhi Intl", "Delhi"),
    "HKG": ("Hong Kong Intl", "Hong Kong"),
    "HND": ("Tokyo Haneda", "Tokyo"),
    "ICN": ("Incheon Intl", "Seoul"),
    "KIX": ("Kansai Intl", "Osaka"),
    "MNL": ("Ninoy Aquino Intl", "Manila"),
    "NRT": ("Narita Intl", "Tokyo"),
    "PEK": ("Beijing Capital Intl", "Beijing"),
    "PVG": ("Shanghai Pudong Intl", "Shanghai"),
    "SGN": ("Tan Son Nhat Intl", "Ho Chi Minh City"),
    "SIN": ("Singapore Changi", "Singapore"),
    "SYD": ("Sydney Kingsford Smith", "Sydney"),
    "TPE": ("Taiwan Taoyuan Intl", "Taipei"),

    # South America
    "BOG": ("El Dorado Intl", "Bogota"),
    "EZE": ("Ministro Pistarini Intl", "Buenos Aires"),
    "GIG": ("Rio de Janeiro-Galeao", "Rio de Janeiro"),
    "GRU": ("Sao Paulo-Guarulhos", "Sao Paulo"),
    "LIM": ("Jorge Chavez Intl", "Lima"),
    "SCL": ("Santiago Intl", "Santiago"),

    # Middle East / Africa
    "ADD": ("Addis Ababa Bole Intl", "Addis Ababa"),
    "AMM": ("Queen Alia Intl", "Amman"),
    "CAI": ("Cairo Intl", "Cairo"),
    "CMN": ("Mohammed V Intl", "Casablanca"),
    "CPT": ("Cape Town Intl", "Cape Town"),
    "DOH": ("Hamad Intl", "Doha"),
    "DXB": ("Dubai Intl", "Dubai"),
    "JNB": ("O.R. Tambo Intl", "Johannesburg"),
    "NBO": ("Jomo Kenyatta Intl", "Nairobi"),
    "TLV": ("Ben Gurion Intl", "Tel Aviv"),

    # Oceania
    "AKL": ("Auckland Airport", "Auckland"),
    "MEL": ("Melbourne Tullamarine", "Melbourne"),
    "PPT": ("Tahiti Faa'a Intl", "Papeete"),

    "FLR": ("Peretola Airport", "Florence"),
    "KOA": ("Ellison Onizuka Kona Intl", "Kona"),

    # North America - US
    "ABQ": ("Albuquerque Intl Sunport", "Albuquerque"),
    "BDL": ("Bradley Intl", "Hartford"),
    "BOI": ("Boise Airport", "Boise"),
    "BUF": ("Buffalo Niagara Intl", "Buffalo"),
    "CMH": ("John Glenn Columbus Intl", "Columbus"),
    "CVG": ("Cincinnati/N Kentucky Intl", "Cincinnati"),
    "DAL": ("Dallas Love Field", "Dallas"),
    "DAY": ("Dayton Intl", "Dayton"),
    "ELP": ("El Paso Intl", "El Paso"),
    "GEG": ("Spokane Intl", "Spokane"),
    "GRR": ("Gerald R. Ford Intl", "Grand Rapids"),
    "JAX": ("Jacksonville Intl", "Jacksonville"),
    "MEM": ("Memphis Intl", "Memphis"),
    "MKE": ("Milwaukee Mitchell Intl", "Milwaukee"),
    "OGG": ("Kahului Airport", "Maui"),
    "OKC": ("Will Rogers World", "Oklahoma City"),
    "OMA": ("Eppley Airfield", "Omaha"),
    "PSP": ("Palm Springs Intl", "Palm Springs"),
    "PVD": ("T.F. Green Intl", "Providence"),
    "RIC": ("Richmond Intl", "Richmond"),
    "RNO": ("Reno-Tahoe Intl", "Reno"),
    "ROC": ("Frederick Douglass Greater Rochester Intl", "Rochester"),
    "SAV": ("Savannah/Hilton Head Intl", "Savannah"),
    "SDF": ("Louisville Muhammad Ali Intl", "Louisville"),
    "SYR": ("Syracuse Hancock Intl", "Syracuse"),
    "TUL": ("Tulsa Intl", "Tulsa"),
    "TUS": ("Tucson Intl", "Tucson"),
    "XNA": ("Northwest Arkansas National", "Bentonville"),

    # North America - Canada
    "YHZ": ("Halifax Stanfield Intl", "Halifax"),
    "YQB": ("Quebec City Jean Lesage Intl", "Quebec City"),
    "YWG": ("Winnipeg James Armstrong Richardson Intl", "Winnipeg"),
    "YXE": ("Saskatoon John G. Diefenbaker Intl", "Saskatoon"),
    "YYJ": ("Victoria Intl", "Victoria"),

    # North America - Mexico / Central America / Caribbean
    "ANU": ("V.C. Bird Intl", "Antigua"),
    "AUA": ("Queen Beatrix Intl", "Aruba"),
    "BGI": ("Grantley Adams Intl", "Barbados"),
    "BZE": ("Philip S. W. Goldson Intl", "Belize City"),
    "CUR": ("Curacao Intl", "Curacao"),
    "GCM": ("Owen Roberts Intl", "Grand Cayman"),
    "GUA": ("La Aurora Intl", "Guatemala City"),
    "HAV": ("Jose Marti Intl", "Havana"),
    "KIN": ("Norman Manley Intl", "Kingston"),
    "MTY": ("Monterrey Intl", "Monterrey"),
    "PLS": ("Providenciales Intl", "Providenciales"),
    "POS": ("Piarco Intl", "Port of Spain"),
    "PTY": ("Tocumen Intl", "Panama City"),
    "SAL": ("El Salvador Intl", "San Salvador"),
    "SJO": ("Juan Santamaria Intl", "San Jose"),
    "STT": ("Cyril E. King Airport", "St. Thomas"),
    "STX": ("Henry E. Rohlsen Airport", "St. Croix"),
    "TIJ": ("Tijuana Intl", "Tijuana"),

    # South America
    "ASU": ("Silvio Pettirossi Intl", "Asuncion"),
    "BSB": ("Brasilia Intl", "Brasilia"),
    "CCS": ("Simon Bolivar Intl", "Caracas"),
    "CTG": ("Rafael Nunez Intl", "Cartagena"),
    "CUZ": ("Alejandro Velasco Astete Intl", "Cusco"),
    "CWB": ("Afonso Pena Intl", "Curitiba"),
    "FOR": ("Pinto Martins Intl", "Fortaleza"),
    "IGU": ("Foz do Iguacu Intl", "Iguazu Falls"),
    "MDE": ("Jose Maria Cordova Intl", "Medellin"),
    "MVD": ("Carrasco Intl", "Montevideo"),
    "POA": ("Salgado Filho Intl", "Porto Alegre"),
    "REC": ("Recife/Guararapes Intl", "Recife"),
    "SSA": ("Salvador Deputado Luis E. Magalhaes Intl", "Salvador"),
    "UIO": ("Mariscal Sucre Intl", "Quito"),
    "VVI": ("Viru Viru Intl", "Santa Cruz"),

    # Europe
    "AAL": ("Aalborg Airport", "Aalborg"),
    "AGP": ("Malaga-Costa del Sol", "Malaga"),
    "ARN": ("Stockholm Arlanda", "Stockholm"),
    "BEG": ("Belgrade Nikola Tesla", "Belgrade"),
    "BER": ("Berlin Brandenburg", "Berlin"),
    "BFS": ("Belfast Intl", "Belfast"),
    "BGO": ("Bergen Airport", "Bergen"),
    "BHX": ("Birmingham Airport", "Birmingham"),
    "BIO": ("Bilbao Airport", "Bilbao"),
    "BLL": ("Billund Airport", "Billund"),
    "BOD": ("Bordeaux-Merignac", "Bordeaux"),
    "BRS": ("Bristol Airport", "Bristol"),
    "BSL": ("EuroAirport Basel-Mulhouse", "Basel"),
    "BUD": ("Budapest Ferenc Liszt Intl", "Budapest"),
    "CGN": ("Cologne Bonn Airport", "Cologne"),
    "DBV": ("Dubrovnik Airport", "Dubrovnik"),
    "FAO": ("Faro Airport", "Faro"),
    "GDN": ("Gdansk Lech Walesa", "Gdansk"),
    "GLA": ("Glasgow Airport", "Glasgow"),
    "GOT": ("Gothenburg Landvetter", "Gothenburg"),
    "HAM": ("Hamburg Airport", "Hamburg"),
    "HER": ("Heraklion Intl", "Heraklion"),
    "IBZ": ("Ibiza Airport", "Ibiza"),
    "INN": ("Innsbruck Airport", "Innsbruck"),
    "KEF": ("Keflavik Intl", "Reykjavik"),
    "KRK": ("Krakow John Paul II Intl", "Krakow"),
    "LJU": ("Ljubljana Joze Pucnik", "Ljubljana"),
    "LPL": ("Liverpool John Lennon", "Liverpool"),
    "LUX": ("Luxembourg Airport", "Luxembourg"),
    "LYS": ("Lyon-Saint Exupery", "Lyon"),
    "NCL": ("Newcastle Airport", "Newcastle"),
    "NUE": ("Nuremberg Airport", "Nuremberg"),
    "OPO": ("Porto Airport", "Porto"),
    "OTP": ("Bucharest Henri Coanda", "Bucharest"),
    "PMI": ("Palma de Mallorca", "Palma de Mallorca"),
    "RHO": ("Rhodes Intl", "Rhodes"),
    "RIX": ("Riga Intl", "Riga"),
    "SKG": ("Thessaloniki Macedonia Intl", "Thessaloniki"),
    "SNN": ("Shannon Airport", "Shannon"),
    "SOF": ("Sofia Airport", "Sofia"),
    "SPU": ("Split Airport", "Split"),
    "STR": ("Stuttgart Airport", "Stuttgart"),
    "SVQ": ("Seville Airport", "Seville"),
    "SZG": ("Salzburg Airport", "Salzburg"),
    "TLL": ("Tallinn Airport", "Tallinn"),
    "TLS": ("Toulouse-Blagnac", "Toulouse"),
    "TRD": ("Trondheim Airport", "Trondheim"),
    "VLC": ("Valencia Airport", "Valencia"),
    "VNO": ("Vilnius Airport", "Vilnius"),
    "WAW": ("Warsaw Chopin Airport", "Warsaw"),
    "ZAG": ("Zagreb Airport", "Zagreb"),

    # Middle East
    "AUH": ("Abu Dhabi Intl", "Abu Dhabi"),
    "BAH": ("Bahrain Intl", "Bahrain"),
    "BEY": ("Beirut-Rafic Hariri Intl", "Beirut"),
    "BGW": ("Baghdad Intl", "Baghdad"),
    "JED": ("King Abdulaziz Intl", "Jeddah"),
    "KWI": ("Kuwait Intl", "Kuwait City"),
    "MCT": ("Muscat Intl", "Muscat"),
    "RUH": ("King Khalid Intl", "Riyadh"),
    "THR": ("Imam Khomeini Intl", "Tehran"),

    # Africa
    "ABJ": ("Felix Houphouet-Boigny Intl", "Abidjan"),
    "ACC": ("Kotoka Intl", "Accra"),
    "ALG": ("Houari Boumediene Airport", "Algiers"),
    "DAR": ("Julius Nyerere Intl", "Dar es Salaam"),
    "DKR": ("Blaise Diagne Intl", "Dakar"),
    "EBB": ("Entebbe Intl", "Kampala"),
    "FIH": ("N'djili Airport", "Kinshasa"),
    "HRE": ("Robert Gabriel Mugabe Intl", "Harare"),
    "KGL": ("Kigali Intl", "Kigali"),
    "LAD": ("Quatro de Fevereiro Airport", "Luanda"),
    "LOS": ("Murtala Muhammed Intl", "Lagos"),
    "LUN": ("Kenneth Kaunda Intl", "Lusaka"),
    "MPM": ("Maputo Intl", "Maputo"),
    "MRU": ("Sir Seewoosagur Ramgoolam Intl", "Mauritius"),
    "RAK": ("Marrakesh Menara Airport", "Marrakesh"),
    "SEZ": ("Seychelles Intl", "Seychelles"),
    "TNR": ("Ivato Intl", "Antananarivo"),
    "TUN": ("Tunis-Carthage Intl", "Tunis"),
    "WDH": ("Hosea Kutako Intl", "Windhoek"),

    # Asia - South & Central
    "ALA": ("Almaty Intl", "Almaty"),
    "AMD": ("Sardar Vallabhbhai Patel Intl", "Ahmedabad"),
    "BLR": ("Kempegowda Intl", "Bangalore"),
    "BOM": ("Chhatrapati Shivaji Maharaj Intl", "Mumbai"),
    "CCU": ("Netaji Subhas Chandra Bose Intl", "Kolkata"),
    "CMB": ("Bandaranaike Intl", "Colombo"),
    "COK": ("Cochin Intl", "Kochi"),
    "DAC": ("Hazrat Shahjalal Intl", "Dhaka"),
    "EVN": ("Zvartnots Intl", "Yerevan"),
    "GOI": ("Goa Intl", "Goa"),
    "GYD": ("Heydar Aliyev Intl", "Baku"),
    "HYD": ("Rajiv Gandhi Intl", "Hyderabad"),
    "ISB": ("Islamabad Intl", "Islamabad"),
    "KHI": ("Jinnah Intl", "Karachi"),
    "KTM": ("Tribhuvan Intl", "Kathmandu"),
    "LHE": ("Allama Iqbal Intl", "Lahore"),
    "MAA": ("Chennai Intl", "Chennai"),
    "TAS": ("Tashkent Intl", "Tashkent"),
    "TBS": ("Tbilisi Intl", "Tbilisi"),
    "ULN": ("Chinggis Khaan Intl", "Ulaanbaatar"),

    # Asia - East & Southeast
    "CAN": ("Guangzhou Baiyun Intl", "Guangzhou"),
    "CEB": ("Mactan-Cebu Intl", "Cebu"),
    "CGK": ("Soekarno-Hatta Intl", "Jakarta"),
    "CJU": ("Jeju Intl", "Jeju"),
    "CKG": ("Chongqing Jiangbei Intl", "Chongqing"),
    "CSX": ("Changsha Huanghua Intl", "Changsha"),
    "CTS": ("New Chitose Airport", "Sapporo"),
    "CTU": ("Chengdu Shuangliu Intl", "Chengdu"),
    "DPS": ("Ngurah Rai Intl", "Bali"),
    "FOC": ("Fuzhou Changle Intl", "Fuzhou"),
    "FUK": ("Fukuoka Airport", "Fukuoka"),
    "GMP": ("Gimpo Intl", "Seoul"),
    "HGH": ("Hangzhou Xiaoshan Intl", "Hangzhou"),
    "HRB": ("Harbin Taiping Intl", "Harbin"),
    "KHH": ("Kaohsiung Intl", "Kaohsiung"),
    "KMG": ("Kunming Changshui Intl", "Kunming"),
    "KOJ": ("Kagoshima Airport", "Kagoshima"),
    "KUL": ("Kuala Lumpur Intl", "Kuala Lumpur"),
    "LXA": ("Lhasa Gonggar Airport", "Lhasa"),
    "NGO": ("Chubu Centrair Intl", "Nagoya"),
    "NKG": ("Nanjing Lukou Intl", "Nanjing"),
    "OKA": ("Naha Airport", "Okinawa"),
    "PNH": ("Phnom Penh Intl", "Phnom Penh"),
    "PUS": ("Gimhae Intl", "Busan"),
    "RGN": ("Yangon Intl", "Yangon"),
    "SHE": ("Shenyang Taoxian Intl", "Shenyang"),
    "SUB": ("Juanda Intl", "Surabaya"),
    "SYX": ("Sanya Phoenix Intl", "Sanya"),
    "SZX": ("Shenzhen Bao'an Intl", "Shenzhen"),
    "TAO": ("Qingdao Jiaodong Intl", "Qingdao"),
    "TSN": ("Tianjin Binhai Intl", "Tianjin"),
    "URC": ("Urumqi Diwopu Intl", "Urumqi"),
    "VTE": ("Wattay Intl", "Vientiane"),
    "WUH": ("Wuhan Tianhe Intl", "Wuhan"),
    "XIY": ("Xi'an Xianyang Intl", "Xi'an"),
    "XMN": ("Xiamen Gaoqi Intl", "Xiamen"),

    # Oceania / Pacific
    "ADL": ("Adelaide Airport", "Adelaide"),
    "APW": ("Faleolo Intl", "Apia"),
    "BNE": ("Brisbane Airport", "Brisbane"),
    "CHC": ("Christchurch Intl", "Christchurch"),
    "CNS": ("Cairns Airport", "Cairns"),
    "DRW": ("Darwin Airport", "Darwin"),
    "GUM": ("Antonio B. Won Pat Intl", "Guam"),
    "HBA": ("Hobart Airport", "Hobart"),
    "NAN": ("Nadi Intl", "Nadi"),
    "OOL": ("Gold Coast Airport", "Gold Coast"),
    "PER": ("Perth Airport", "Perth"),
    "POM": ("Jacksons Intl", "Port Moresby"),
    "VLI": ("Bauerfield Intl", "Port Vila"),
    "WLG": ("Wellington Intl", "Wellington"),
    "ZQN": ("Queenstown Airport", "Queenstown"),
}

# ── Truncated name -> IATA code ───────────────────────────────
# Maps the truncated city names that appear in old-format invoices.
# Key is UPPERCASE, matched against the raw parsed city name.
TRUNCATED = {
    # Exact matches (no truncation)
    "DENVER": "DEN",
    "MARSEILLE": "MRS",
    "VANCOUVER": "YVR",
    "ANCHORAGE": "ANC",
    "BARCELONA": "BCN",
    "LISBON": "LIS",
    "LONDON": "LHR",
    "PARIS": "CDG",
    "ROME": "FCO",
    "TOKYO": "NRT",
    "AMSTERDAM": "AMS",
    "DUBLIN": "DUB",
    "FRANKFURT": "FRA",
    "MUNICH": "MUC",
    "VENICE": "VCE",
    "ZURICH": "ZRH",
    "HONG KONG": "HKG",
    "SINGAPORE": "SIN",
    "SYDNEY": "SYD",
    "MIAMI": "MIA",
    "BOSTON": "BOS",
    "ATLANTA": "ATL",
    "ORLANDO": "MCO",
    "DALLAS": "DFW",
    "HOUSTON": "IAH",
    "PHOENIX": "PHX",
    "PORTLAND": "PDX",
    "HONOLULU": "HNL",
    "NASHVILLE": "BNA",
    "CANCUN": "CUN",
    "MONTREAL": "YUL",
    "TORONTO": "YYZ",
    "EDMONTON": "YEG",
    "CALGARY": "YYC",
    "OTTAWA": "YOW",

    # Truncated names from old-format invoices
    "SAN FRANCISCO/SAN FRANC": "SFO",
    "SAN FRANCISCO": "SFO",
    "SEATTLE/TACOMA INTERNAT": "SEA",
    "SEATTLE/TACOMA": "SEA",
    "SEATTLE": "SEA",
    "TORONTO/LESTER B PEARSO": "YYZ",
    "TORONTO/LESTER B PEARSON": "YYZ",
    "LOS ANGELES/LOS ANGELE": "LAX",
    "LOS ANGELES": "LAX",
    "NEW YORK/JOHN F KENNED": "JFK",
    "NEW YORK/JOHN F KENNEDY": "JFK",
    "NEW YORK/NEWARK": "EWR",
    "NEW YORK/LAGUARDIA": "LGA",
    "WASHINGTON/DULLES INTER": "IAD",
    "WASHINGTON/DULLES": "IAD",
    "WASHINGTON/NATIONAL": "DCA",
    "CHICAGO/O'HARE INTERNA": "ORD",
    "CHICAGO/O'HARE": "ORD",
    "CHICAGO/OHARE": "ORD",
    "CHICAGO": "ORD",
    "DALLAS/FORT WORTH INTE": "DFW",
    "DALLAS/FORT WORTH": "DFW",
    "HOUSTON/GEORGE BUSH IN": "IAH",
    "HOUSTON/GEORGE BUSH": "IAH",
    "LAS VEGAS": "LAS",
    "SAN DIEGO": "SAN",
    "SAN JOSE": "SJC",
    "SALT LAKE CITY": "SLC",
    "MINNEAPOLIS/ST PAUL IN": "MSP",
    "MINNEAPOLIS": "MSP",
    "DETROIT/METROPOLITAN W": "DTW",
    "DETROIT": "DTW",
    "CHARLOTTE": "CLT",
    "PHILADELPHIA": "PHL",
    "FORT LAUDERDALE": "FLL",
    "TAMPA": "TPA",
    "NEW ORLEANS": "MSY",
    "PARIS/CHARLES DE GAULL": "CDG",
    "PARIS/CHARLES DE GAULLE": "CDG",
    "PARIS/ORLY": "ORY",
    "LONDON/HEATHROW": "LHR",
    "LONDON/GATWICK": "LGW",
    "LONDON/STANSTED": "STN",
    "ROME/FIUMICINO": "FCO",
    "MILAN/MALPENSA": "MXP",
    "MADRID": "MAD",
    "ISTANBUL": "IST",
    "DUBAI": "DXB",
    "DOHA": "DOH",
    "MEXICO CITY": "MEX",
    "SAO PAULO": "GRU",
    "BUENOS AIRES": "EZE",
    "BANGKOK": "BKK",
    "SEOUL/INCHEON": "ICN",
    "SARASOTA": "SRQ",
    "SACRAMENTO": "SMF",
    "OAKLAND": "OAK",
    "SAN ANTONIO": "SAT",
    "FORT MYERS": "RSW",
    "WEST PALM BEACH": "PBI",
    "KANSAS CITY": "MCI",
    "CLEVELAND": "CLE",
    "INDIANAPOLIS": "IND",
    "AUSTIN": "AUS",
    "ST LOUIS": "STL",
    "RALEIGH": "RDU",
    "PITTSBURGH": "PIT",
    "BURBANK": "BUR",
    "FLORENCE": "FLR",
    "KONA": "KOA",
    "KONA/KAILUA": "KOA",

    # Additional major international airports
    "ABIDJAN": "ABJ",
    "ABU DHABI": "AUH",
    "ACCRA": "ACC",
    "ADELAIDE": "ADL",
    "ALBUQUERQUE": "ABQ",
    "ALGIERS": "ALG",
    "ALMATY": "ALA",
    "ANTANANARIVO": "TNR",
    "BAGHDAD": "BGW",
    "BAHRAIN": "BAH",
    "BAKU": "GYD",
    "BALI": "DPS",
    "BANGALORE": "BLR",
    "BEIRUT": "BEY",
    "BELFAST": "BFS",
    "BELGRADE": "BEG",
    "BERLIN": "BER",
    "BILBAO": "BIO",
    "BIRMINGHAM": "BHX",
    "BOISE": "BOI",
    "BORDEAUX": "BOD",
    "BRISBANE": "BNE",
    "BRISTOL": "BRS",
    "BUCHAREST": "OTP",
    "BUDAPEST": "BUD",
    "BUFFALO": "BUF",
    "BUSAN": "PUS",
    "CAIRNS": "CNS",
    "CARACAS": "CCS",
    "CEBU": "CEB",
    "CHENGDU": "CTU",
    "CHENNAI": "MAA",
    "CHONGQING": "CKG",
    "CHRISTCHURCH": "CHC",
    "CINCINNATI": "CVG",
    "COLOGNE": "CGN",
    "COLOMBO": "CMB",
    "COLUMBUS": "CMH",
    "DAKAR": "DKR",
    "DAR ES SALAAM": "DAR",
    "DARWIN": "DRW",
    "DHAKA": "DAC",
    "FARO": "FAO",
    "FUKUOKA": "FUK",
    "GLASGOW": "GLA",
    "GOLD COAST": "OOL",
    "GOTHENBURG": "GOT",
    "GUAM": "GUM",
    "GUANGZHOU": "CAN",
    "GUATEMALA CITY": "GUA",
    "HALIFAX": "YHZ",
    "HAMBURG": "HAM",
    "HANGZHOU": "HGH",
    "HARARE": "HRE",
    "HARTFORD": "BDL",
    "HAVANA": "HAV",
    "HOBART": "HBA",
    "HYDERABAD": "HYD",
    "INNSBRUCK": "INN",
    "ISLAMABAD": "ISB",
    "JAKARTA": "CGK",
    "JEDDAH": "JED",
    "JEJU": "CJU",
    "KAMPALA": "EBB",
    "KAOHSIUNG": "KHH",
    "KARACHI": "KHI",
    "KATHMANDU": "KTM",
    "KIGALI": "KGL",
    "KINGSTON": "KIN",
    "KINSHASA": "FIH",
    "KOLKATA": "CCU",
    "KRAKOW": "KRK",
    "KUALA LUMPUR": "KUL",
    "KUNMING": "KMG",
    "KUWAIT CITY": "KWI",
    "LAGOS": "LOS",
    "LAHORE": "LHE",
    "LHASA": "LXA",
    "LIVERPOOL": "LPL",
    "LJUBLJANA": "LJU",
    "LUANDA": "LAD",
    "LUSAKA": "LUN",
    "LUXEMBOURG": "LUX",
    "LYON": "LYS",
    "MALAGA": "AGP",
    "MAPUTO": "MPM",
    "MARRAKESH": "RAK",
    "MAURITIUS": "MRU",
    "MEDELLIN": "MDE",
    "MEMPHIS": "MEM",
    "MILWAUKEE": "MKE",
    "MONTEVIDEO": "MVD",
    "MUMBAI": "BOM",
    "MUSCAT": "MCT",
    "NADI": "NAN",
    "NAGOYA": "NGO",
    "NANJING": "NKG",
    "OKLAHOMA CITY": "OKC",
    "OMAHA": "OMA",
    "PANAMA CITY": "PTY",
    "PERTH": "PER",
    "PHNOM PENH": "PNH",
    "PORT MORESBY": "POM",
    "PORTO": "OPO",
    "QUEENSTOWN": "ZQN",
    "QUITO": "UIO",
    "RENO": "RNO",
    "REYKJAVIK": "KEF",
    "RIGA": "RIX",
    "RIYADH": "RUH",
    "SALZBURG": "SZG",
    "SAPPORO": "CTS",
    "SEVILLE": "SVQ",
    "SEYCHELLES": "SEZ",
    "SHENZHEN": "SZX",
    "SOFIA": "SOF",
    "STOCKHOLM": "ARN",
    "STUTTGART": "STR",
    "SURABAYA": "SUB",
    "TALLINN": "TLL",
    "TASHKENT": "TAS",
    "TBILISI": "TBS",
    "TEHRAN": "THR",
    "TIANJIN": "TSN",
    "TOULOUSE": "TLS",
    "TUCSON": "TUS",
    "TUNIS": "TUN",
    "ULAANBAATAR": "ULN",
    "URUMQI": "URC",
    "VALENCIA": "VLC",
    "VIENTIANE": "VTE",
    "VILNIUS": "VNO",
    "WARSAW": "WAW",
    "WELLINGTON": "WLG",
    "WINDHOEK": "WDH",
    "WINNIPEG": "YWG",
    "WUHAN": "WUH",
    "XIAMEN": "XMN",
    "YANGON": "RGN",
    "YEREVAN": "EVN",
    "ZAGREB": "ZAG",
}


def lookup_airport(city_name: str) -> dict:
    """
    Look up a city name (possibly truncated) and return full airport info.

    Returns: {
        "iata": "SFO",
        "airport": "San Francisco Intl",
        "city": "San Francisco",
        "display": "San Francisco Intl (SFO)"
    }
    or None if not found (falls back to original name).
    """
    if not city_name:
        return None

    key = city_name.strip().upper()

    # Try exact match in truncated map
    if key in TRUNCATED:
        code = TRUNCATED[key]
        if code in IATA:
            airport, city = IATA[code]
            return {
                "iata": code,
                "airport": airport,
                "city": city,
                "display": f"{airport}, {city} ({code})",
            }

    # Try prefix match (for unknown truncations)
    for trunc_name, code in TRUNCATED.items():
        if key.startswith(trunc_name[:8]) and code in IATA:
            airport, city = IATA[code]
            return {
                "iata": code,
                "airport": airport,
                "city": city,
                "display": f"{airport}, {city} ({code})",
            }

    return None


def resolve_city(city_name: str) -> str:
    """
    Return a clean display string for a city name.
    If found in lookup: "San Francisco Intl, San Francisco (SFO)"
    If not found: title-cased original name.
    """
    result = lookup_airport(city_name)
    if result:
        return result["display"]
    # Clean up the raw name
    return " ".join(w.capitalize() for w in city_name.lower().split("/")[0].split())


if __name__ == "__main__":
    # Test with known truncated names
    tests = [
        "DENVER",
        "VANCOUVER",
        "ANCHORAGE",
        "SEATTLE/TACOMA INTERNAT",
        "SAN FRANCISCO/SAN FRANC",
        "TORONTO/LESTER B PEARSO",
        "BARCELONA",
        "LISBON",
        "UNKNOWN CITY",
    ]
    for t in tests:
        print(f"  {t:30} -> {resolve_city(t)}")